#!/usr/bin/env bash

factorial() {
  no=$1
  fact=1
  while [ $no -gt 0 ]
  do
    fact=$((fact * no))
    no=$((no-1))
  done
  echo "The factorial of $1 is $fact."
}

palindrome() {
  NUM=$1
  REV=0
  while [ $NUM -gt 0 ]
  do
    REV=$((REV * 10 + NUM % 10))
    NUM=$((NUM / 10))
  done
  if [ $REV = $1 ]
  then
    echo "$1 is a palindrome."
  else
    echo "$1 is not a Palindrome."
  fi
}

fibonacci() {
  count=$1
  a=-1
  b=1
  for(( i=0 ; i < $1 ; i++ ))
  do
    val=$((a+b))
    echo -n "$val "
    a=$b
    b=$val
    count=$((count-1))
  done
  echo
}

primeno() {
  n=$1/2
  for(( i=2 ; i <= n ; i++))
  do
    if [ $(($1%i)) = 0 ]
    then
      echo "$1 is a not prime number."
      return
    fi
  done
  echo "$1 is a prime number."
}

echo "Menu:"
echo "1: Find Factorial"
echo "2: Check Palindrome"
echo "3: Print Fibonacci Series"
echo "4: Check if Prime"
read -p "Enter your choice: " ch

case $ch in
1) factorial $1;;
2) palindrome $1;;
3) fibonacci $1;;
4) primeno $1;;
*) echo "Invalid Option!"
esac

exit 0 
